[package]
name = "deploy-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.11"
ssh2 = "0.9.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.8"
chrono = "0.4"
zip = "0.6"
walkdir = "2.4"